.dashParticles_js_metadata <- function() {
deps_metadata <- list(`dash_particles` = structure(list(name = "dash_particles",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashParticles.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashParticles",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_particles` = structure(list(name = "dash_particles",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-DashParticles.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashParticles",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_particles` = structure(list(name = "dash_particles",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_particles.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashParticles",
all_files = FALSE), class = "html_dependency"),
`dash_particles` = structure(list(name = "dash_particles",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_particles.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashParticles",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
